# Generated by Django 6.1 on 2026-08-22 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name="identifiant d'URL")),
                ('est_active', models.BooleanField(default=True, help_text='Décocher pour masquer la catégorie sans supprimer les liens existants.', verbose_name='active')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name="identifiant d'URL")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='plats/%Y/%m', verbose_name='image')),
                ('nombre_personnes', models.PositiveSmallIntegerField(default=4, verbose_name='nombre de personnes')),
                ('temps_preparation_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='temps de préparation (minutes)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('categories', models.ManyToManyField(blank=True, related_name='plats', to='plats.categorie', verbose_name='catégories')),
                ('plat_origine', models.ForeignKey(blank=True, help_text="Renseigné lorsque ce plat est la copie du plat d'un autre membre.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='plats.plat', verbose_name="plat d'origine")),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'plat',
                'verbose_name_plural': 'plats',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['nom'], name='plats_plat_nom_c6371b_idx'), models.Index(fields=['-date_creation'], name='plats_plat_date_cr_d299de_idx')],
            },
        ),
    ]
