# Generated by Django 6.1 on 2026-08-22 14:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0002_categories_initiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCuisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(260)], verbose_name='température (°C)')),
                ('duree_minutes', models.PositiveSmallIntegerField(help_text="Toujours en minutes, même au-delà d'une heure.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='durée (minutes)')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='note')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('date_test', models.DateField(default=django.utils.timezone.localdate, verbose_name='date du test')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="date d'enregistrement")),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='plats.plat', verbose_name='plat')),
            ],
            options={
                'verbose_name': 'test de cuisson',
                'verbose_name_plural': 'tests de cuisson',
                'ordering': ['-date_test', '-id'],
            },
        ),
        migrations.AddField(
            model_name='plat',
            name='meilleur_test',
            field=models.ForeignKey(blank=True, help_text='Test choisi manuellement comme meilleure cuisson de ce plat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plats.testcuisson', verbose_name='meilleure combinaison'),
        ),
        migrations.AddIndex(
            model_name='testcuisson',
            index=models.Index(fields=['plat', '-date_test'], name='plats_testc_plat_id_bf28ce_idx'),
        ),
    ]
