# Generated by Django 6.1 on 2026-08-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0003_tests_de_cuisson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='plats.plat', verbose_name='plat')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL, verbose_name='membre')),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
                'ordering': ['-date_ajout'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'plat'), name='favori_unique_par_membre_et_plat')],
            },
        ),
    ]
