# Generated by Django 6.1 on 2026-08-22 15:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0004_favori'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('texte', models.TextField(verbose_name='étape')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='plats.plat', verbose_name='plat')),
            ],
            options={
                'verbose_name': 'étape de préparation',
                'verbose_name_plural': 'étapes de préparation',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='ingrédient')),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour une quantité libre (« sel », « poivre »).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantité')),
                ('unite', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('cl', 'cl'), ('l', 'l'), ('cc', 'cuillère à café'), ('cs', 'cuillère à soupe'), ('pincee', 'pincée'), ('tranche', 'tranche')], help_text='Vide pour compter en pièces (« 2 œufs »).', max_length=10, verbose_name='unité')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='plats.plat', verbose_name='plat')),
            ],
            options={
                'verbose_name': 'ingrédient',
                'verbose_name_plural': 'ingrédients',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
