# Generated by Django 6.1 on 2026-08-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0005_etapepreparation_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcuisson',
            name='note',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='note'),
        ),
    ]
