# Generated by Django 6.1 on 2026-08-30 16:36

import plats.validateurs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0006_libelles_de_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, help_text='Facultative, 5 Mo maximum.', upload_to='plats/%Y/%m', validators=[plats.validateurs.valider_taille_image], verbose_name='image'),
        ),
    ]
