# Generated by Django 6.1 on 2026-09-05 13:54

import plats.validateurs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0007_limite_taille_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, help_text='Facultative. Elle est recadrée et allégée automatiquement, inutile de la préparer : au moins 280 pixels de large, 15 Mo maximum.', upload_to='plats/%Y/%m', validators=[plats.validateurs.valider_taille_image], verbose_name='image'),
        ),
    ]
